platform: linux

image_resource:
  type: docker-image
  source:
    repository: hashicorp/terraform
    tag: "0.11.8"

inputs:
- name: terraform

outputs:
- name: updated_source

params:
  github_token: ((github_token))

run:
  path: source/concourse/tasks/terraform/checkin.sh
